version: 2.1
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

  tests:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Run Lint Test
          command: ./gradlew lint
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

  deploy:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Build Library
          command: ./gradlew :expandable-recyclerview:assembleRelease
      - run:
          name: Export key
          command: |
            mkdir expandable-recyclerview/maven
            echo ${GPG_KEY_CONTENTS} | base64 -d --ignore-garbage > expandable-recyclerview/maven/secret.gpg
      - run:
          name: Staging
          command: ./gradlew :expandable-recyclerview:publishReleasePublicationToSonatypeRepository
      - run:
          name: Release Library
          command: ./gradlew closeAndReleaseRepository

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]{1,3}\.[0-9]{1,3}\.?[0-9]{0,3}.*/
            branches:
              ignore: /.*/