name: Test

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      # Builds the release artifacts
      - name: Build project
        run: ./gradlew assemble

      # Run tests
      - name: Run tests
        run: ./gradlew test
